name: PHP Code Sniffer
on: pull_request
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP CodeSniffer
        run: |
          cd .github/codesniff
          composer require --dev dealerdirect/phpcodesniffer-composer-installer
          composer require --dev drupal/coder
      - name: Check coding standards
        run: |
          cd .github/codesniff
          vendor/bin/phpcs
